// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	Balance       float64   `json:"balance"`
	CurrencyID    int64     `json:"currency_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	AccountNumber string    `json:"account_number"`
}

type Currency struct {
	ID             int64          `json:"id"`
	CurrencyString string         `json:"currency_string"`
	CurrencyName   sql.NullString `json:"currency_name"`
	Starter        sql.NullInt32  `json:"starter"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    float64   `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type MoneyRecord struct {
	ID        int64   `json:"id"`
	UserID    int64   `json:"user_id"`
	Reference string  `json:"reference"`
	Status    string  `json:"status"`
	Amount    float64 `json:"amount"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	Amount        float64   `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
